### ISSUE TITLE
Update supermarket

### ISSUE THREAD

**Issue by PierreRambaud** [spheromak/dhcp-cook#43]
Hi,

Latest update on supermarket was released in 2012, can you update with the latest version?

Regards

**Comment by PierreRambaud** [comment]
Ping*

**Comment by jmccann** [comment]
I'd like to know about this also.  Is this cookbook planned on continuing to be maintained?  Supermarket not updated with latest version, issues with no responses, no new commits for 10+ months.

I'd like to help clean this up, and have even submitted some PRs fixing some issues.  But if they are not going to be merged perhaps I am wasting my time?

Additionally, you can put cookbooks up for adoption: https://supermarket.chef.io/available_for_adoption

So please let us know the status of this cookbook.  :smile:

**Comment by PierreRambaud** [comment]
:+1:

**Comment by spheromak** [comment]
Hey guys. I am still paying attention her :)  I just missed the issue/pr's that got opened. I am no longer using this cookbook day to day. If one of you want to take it over I would be happy to hand it over.

**Comment by jmccann** [comment]
@spheromak I wouldn't mind taking it over.  I have other contributions I can make that I've not tried contributing back yet.  :smile:

**Comment by PierreRambaud** [comment]
It can be cool to move this cookbook into chef-brigade or redguide organizations instead of having one owner

**Comment by spheromak** [comment]
@PierreRambaud Im ok with that.  Where do I find info on that.

**Comment by spheromak** [comment]
@PierreRambaud @jmccann  I have moved this cookbook into the chef-brigade. If you or anyone else is interested in maintaining it you can join the brigade, and take it over. 

Thanks for the suggestion
